namespace Skua.Core.Generators;
internal static class Attributes
{
    public const string MethodCallBindingFullName = "Skua.Core.Flash.MethodCallBindingAttribute";
    public const string MethodCallBindingName = "MethodCallBinding";
    public const string MethodCallBindingSource =
@"using System;

// <auto-generated>

namespace Skua.Core.Flash
{
    [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    sealed class MethodCallBindingAttribute : Attribute
    {
        public string Name { get; set; }
        public bool RunMethodPre { get; set; }
        public bool RunMethodPost { get; set; }
        public bool GameFunction { get; set; }
        public bool ParseFromJson { get; set; }
        public string? Default { get; set; }

        public MethodCallBindingAttribute(string name)
        {
            Name = name;
        }
    }
}
";


    public const string ModuleBindingFullName = "Skua.Core.Flash.ModuleBindingAttribute";
    public const string ModuleBindingName = "ModuleBinding";
    public const string ModuleBindingSource =
@"using System;

// <auto-generated>

namespace Skua.Core.Flash
{
    [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    sealed class ModuleBindingAttribute : Attribute
    {
        public string Name { get; set; }

        public ModuleBindingAttribute(string name)
        {
            Name = name;
        }
    }
}
";

    public const string CallBindingFullName = "Skua.Core.Flash.CallBindingAttribute";
    public const string CallBindingName = "CallBinding";
    public const string CallBindingSource =
@"using System;

// <auto-generated>

namespace Skua.Core.Flash
{
    [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    sealed class CallBindingAttribute : Attribute
    {
        public string Name { get; set; }
        public bool UseValue { get; set; }
        public bool Get { get; set; }
        public bool Set { get; set; }
        public bool HasSetter { get; set; }
        public string? Default { get; set; }

        public CallBindingAttribute(string name)
        {
            Name = name;
        }
    }
}
";
    public const string ObjectBindingFullName = "Skua.Core.Flash.ObjectBindingAttribute";
    public const string ObjectBindingName = "ObjectBinding";
    public const string ObjectBindingSource =
@"using System;

// <auto-generated>

#nullable disable warnings
namespace Skua.Core.Flash
{
    [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    sealed class ObjectBindingAttribute : Attribute
    {
        public string[] Paths { get; set; }
        public bool Get { get; set; }
        public bool Set { get; set; }
        public string? Select { get; set; }
        public string? RequireNotNull { get; set; }
        public string? Default { get; set; }
        public bool IsStatic { get; set; }
        public bool HasSetter { get; set; }

        public ObjectBindingAttribute(params string[] paths)
        {
            Paths = paths;
        }
    }
}
";

    public const string JsonCallBindingFullName = "Skua.Core.Flash.JsonCallBindingAttribute";
    public const string JsonCallBindingName = "JsonCallBinding";
    public const string JsonCallBindingSource =
@"using System;

// <auto-generated>

namespace Skua.Core.Flash
{
    [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    sealed class JsonCallBindingAttribute : Attribute
    {
        public string FunctionName { get; set; }
        public bool Get { get; set; }
        public bool HasSetter { get; set; }
        public string? Default { get; set; }

        public JsonCallBindingAttribute(string functionName)
        {
            FunctionName = functionName;
        }
    }
}
";
}
