//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skua.App.WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Tercessuinotlim,tercessuinotlim,Enter,Spawn</string>
  <string>Nulgath,tercessuinotlim,Boss2,Right</string>
  <string>VHL &amp; Taro,tercessuinotlim,Taro,Left</string>
  <string>Swindle,tercessuinotlim,Swindle,Left</string>
  <string>Polish,tercessuinotlim,m12,Right</string>
  <string>Yin &amp; Yang,tercessuinotlim,Twins,Left</string>
  <string>Carnage,tercessuinotlim,m4,Right</string>
  <string>Lae,tercessuinotlim,m5,Top</string>
  <string>Binky,doomvault,r5,Left</string>
  <string>Museum,museum,Crossroad,Left</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FastTravels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FastTravels"]));
            }
            set {
                this["FastTravels"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Tercessuinotlim,tercessuinotlim,Enter,Spawn</string>
  <string>Nulgath,tercessuinotlim,Boss2,Right</string>
  <string>VHL &amp; Taro,tercessuinotlim,Taro,Left</string>
  <string>Swindle,tercessuinotlim,Swindle,Left</string>
  <string>Polish,tercessuinotlim,m12,Right</string>
  <string>Yin &amp; Yang,tercessuinotlim,Twins,Left</string>
  <string>Carnage,tercessuinotlim,m4,Right</string>
  <string>Lae,tercessuinotlim,m5,Top</string>
  <string>Binky,doomvault,r5,Left</string>
  <string>Museum,museum,Crossroad,Left</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultFastTravels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultFastTravels"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Skua,Dark,#FF607D8B,#FF607D8B,#FF000000,#FF000000,true,4.5,Medium,All</string>
  <string>RBot,Light,#FF9C934E,#FF9C934E,#FF000000,#FF000000</string>
  <string>Grimoire,Dark,#FFCC1F41,#FFCC1F41,#FFFFFFFF,#FFFFFFFF</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultThemes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultThemes"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UserThemes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserThemes"]));
            }
            set {
                this["UserThemes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Skua,Dark,#FF607D8B,#FF607D8B,#FF000000,#FF000000,true,4.5,Medium,All")]
        public string CurrentTheme {
            get {
                return ((string)(this["CurrentTheme"]));
            }
            set {
                this["CurrentTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UserOptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UserOptions"]));
            }
            set {
                this["UserOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserGitHubToken {
            get {
                return ((string)(this["UserGitHubToken"]));
            }
            set {
                this["UserGitHubToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int AnimationFrameRate {
            get {
                return ((int)(this["AnimationFrameRate"]));
            }
            set {
                this["AnimationFrameRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoUpdateScripts {
            get {
                return ((bool)(this["AutoUpdateScripts"]));
            }
            set {
                this["AutoUpdateScripts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckClientUpdates {
            get {
                return ((bool)(this["CheckClientUpdates"]));
            }
            set {
                this["CheckClientUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckClientPrereleases {
            get {
                return ((bool)(this["CheckClientPrereleases"]));
            }
            set {
                this["CheckClientPrereleases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckScriptUpdates {
            get {
                return ((bool)(this["CheckScriptUpdates"]));
            }
            set {
                this["CheckScriptUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreGHAuth {
            get {
                return ((bool)(this["IgnoreGHAuth"]));
            }
            set {
                this["IgnoreGHAuth"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0.1.0")]
        public string ApplicationVersion {
            get {
                return ((string)(this["ApplicationVersion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseLocalVSC {
            get {
                return ((bool)(this["UseLocalVSC"]));
            }
            set {
                this["UseLocalVSC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ToggleScript|F10</string>
  <string>LoadScript|F9</string>
  <string>OpenBank|F2</string>
  <string>OpenConsole|F3</string>
  <string>ToggleAutoAttack|F4</string>
  <string>ToggleAutoHunt|F5</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HotKeys {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HotKeys"]));
            }
            set {
                this["HotKeys"] = value;
            }
        }
    }
}
